language: php

php:
  - 5.5


env:
  global:
    # Your Pantheon site's UUID (e.g. from your dashboard URL)
    - PUUID='f006720e-7c7f-4c71-a692-911780c1d6fc'

    # Your Pantheon site's name.
    - PNAME='golden-god-demo'

    # SECRET/PRIVATE VARIABLES
    #
    # These are created by using the travis command locally to encrypt some values.
    #
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    # PEMAIL environment variable: represents the Pantheon account e-mail with
    # access to this site. Used to authenticate to Pantheon via Terminus. You
    # must cd to your project root and run:
    #
    # travis encrypt PEMAIL='test@example.com'
    #
    - secure: "lgybTlfvn8PXn1CglWCvr7BXeIPABvMZNuURcb1OZaTlv0FWzA6AdirdcUO70vnKQqJzDFQwtE1Zuk7TqM0gs9aSYl3o2rDs8+BaMQK+dQtLi06wMcecBNIWfnBoDjFv54eiv1adQWmitSChi/KlbJGfeD7oLVEVheAKYbzQau1kQGG+K0QnvMx3ChatH3hEb+aQ54u99WJFvxpZOOwynmozSUfEtVFtkhyhzui11GiSXqDTJL9PcmwpWdRtMdtj3lEY2AuWGdf8ybNcWumgzp2f8PnqniZWmXsrDHBpKe6hEty9K0iRxRuG+g99101/DR29LLELXNwD1mI4hLt8fi9595nCVrO+eHl5jeNskk8hbcBddSoqGEfMJSycbvNVttSu3XLAr/EDowpr84gfFeoAKXzIbstXPliQ7UvuJ4Z/RxBmCIZAScpdenkSww0apD1id5f38614H3pDLNgfJajabp1P4/NHjleNgx5xrdDwovsoLBq77okasnFxGD6IZ5vji9SOBImbDzyKOjXTFe6Ef06TsZsXsfYfdQyohLQ9wn+T895QT2onJkOCSJ1UGTaEMv9hCwnIGsuQtrggWjlGwmFxkE2WEFU3KUdEMwFdFzcm1QR0sYHNiSm3k6y0knzqxtp7z8mSLNdMCVL4Q6Gp7f4iuWpGRDlF5NDhdBU="

    #
    # PPASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt PPASS='my_account_password'
    #
    - secure: "JAdEX53pR/ogkoWaV0jtwPEXPNlTkEEKFn8BqCPr3QvR8caOoDFB231LfvCXdoZ/dXkpBkPU7nVE56SwiR+KYPP0WSYawXaW1FAToBS+ot0j0Em1x49Z+MO67W3psCrM3gorB5GpqAwi3qtQI7+lqylise2ZIV2f6B5y9kyGAcMleq5IrpAK2OS6iCiDHVXjYM82c08CcvcWkPqkTdRYzAyVG9lowcOHj3DomSUluyDjXPrDP/2D/+YR1i4OptrZ2J9j9vrhWMMOwMq5LA+L12tkv1Ze6rmpRG9pG1PXkyMCiNVawgMTQx8FrBqIVDNv6cuCB5apxi23Pey2TzR2F73bVy2gOisYBahhZPFLqU9Dz7Z4A/k/yY9mTAMdmZKIcGwgiGEAaetz985O8dE1tKev1NDM/TdMFyHy32jChfUOlGUvbGsO5GDxM48pCG4PlvSRXLmxpc1yVEX/owtw2AMQ3eVe6xZu0evW76MiG5UE6hQr6t34pLDmw+FoNLhUfxm7Kom+0e8roQEZxLePZFpTxWBZ0fx+7qEzJrZjjY54TUhr4TXn//pcV29OoZ0B9Fgc6d0dGTzxJyEV8ltpubesxfdvfhkpnDjD7eKUCfp/2hwtOkbt1Y21bwNHe5UhrJxuugRPyA3XH9mAUg/Uq5U6imItc0bMrBBBSIawTL0="

before_install:
    # Place a passphrase-free ssh key so that you can clone and push to your
    # Pantheon git repository.
    #
    # Use the travis encrypt-file command to generate your own.
    #
    # See: http://docs.travis-ci.com/user/encrypting-files/
    #
    - openssl aes-256-cbc -K $encrypted_c8f15b38deee_key -iv $encrypted_c8f15b38deee_iv -in pantheon_bot_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 0600 ~/.ssh/id_rsa

install:
    - bash private/scripts/install.sh

before_script:
  # Could add more things to prep for the test run here.

script:
    - bash private/scripts/test.sh

after_script:
  # General-purpose clean-up could go here.

after_success:
  # Maybe promote to test here?

after_failure:
  # Maybe roll back?

notifications:
  email:
    recipients:
      # - panopoly-ci@googlegroups.com
    on_success: always
    on_failure: always
